name: cicd-workflow with slack integration

on:
  push:
    branches:
      - main
    paths:
      - '**/*.eme'   # ✅ Only trigger when .eme files are changed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GITHUB_INTEGRATION_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Notify Slack of .eme file change
        uses: act10ns/slack@v2
        with:
          channel: 'Notify Slack of .eme file change'
          status: ${{ job.status }}
          fields: |
            *Repo:* ${{ github.repository }}
            *Branch:* ${{ github.ref_name }}
            *Commit:* ${{ github.sha }}
            *Actor:* ${{ github.actor }}
            *Message:* ${{ github.event.head_commit.message }}
        if: always()
