name: ALERT !!!
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GITHUB_INTEGRATION_URL }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build with Maven
      run: mvn install -f MyWebApp/pom.xml
    - uses: act10ns/slack@v2
      with:
        channel: 'github-eme-file-modification'
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()
